# Generated by Django 5.1.3 on 2025-11-26 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version number (e.g., 1.0.0)', max_length=50, unique=True)),
                ('file', models.FileField(help_text='Firmware binary file (.bin)', upload_to='firmware/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bin'])])),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active versions are available for OTA updates')),
                ('release_notes', models.TextField(blank=True, help_text='Release notes and changelog')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
            ],
            options={
                'verbose_name': 'Firmware Version',
                'verbose_name_plural': 'Firmware Versions',
                'ordering': ['-release_date'],
            },
        ),
    ]
