# Generated by Django 5.1.3 on 2025-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicecapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ir_sensor_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('motion_detected', 'Motion Detected')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='last_motion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
