# Generated by Django 5.1.3 on 2025-11-26 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_ir_sensor_status_device_last_motion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='connection_type',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('cellular', 'Cellular'), ('unknown', 'Unknown')], default='unknown', help_text='Current connection type (WiFi or Cellular)', max_length=20),
        ),
        migrations.AddField(
            model_name='devicecapture',
            name='connection_type',
            field=models.CharField(choices=[('wifi', 'WiFi'), ('cellular', 'Cellular'), ('unknown', 'Unknown')], default='unknown', help_text='Connection type used for this capture', max_length=20),
        ),
        migrations.AddField(
            model_name='devicecapture',
            name='data_size_bytes',
            field=models.IntegerField(default=0, help_text='Size of capture data in bytes'),
        ),
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(help_text='SIM card ICCID', max_length=20, unique=True)),
                ('plan_mb', models.IntegerField(default=0, help_text='Data plan limit in MB')),
                ('data_used_mb', models.FloatField(default=0.0, help_text='Data used in MB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_cards', to='devices.device')),
            ],
            options={
                'verbose_name': 'SIM Card',
                'verbose_name_plural': 'SIM Cards',
                'ordering': ['-updated_at'],
            },
        ),
    ]
