# Generated by Django 5.1.3 on 2025-11-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_captureanalysis_email_acknowledgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captureanalysis',
            name='email_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
