# Generated by Django 5.1.3 on 2025-11-26 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_migrate_pushsubscription_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captureanalysis',
            options={'ordering': ['-analysis_timestamp'], 'verbose_name': 'Capture Analysis', 'verbose_name_plural': 'Capture Analyses'},
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='analysis_timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When analysis was performed'),
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='bounding_boxes',
            field=models.JSONField(default=list, help_text='Bounding box coordinates for detected objects'),
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Overall confidence score (0.0-1.0)', null=True),
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='email_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When customer replied', null=True),
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Email notification sent'),
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When email was sent', null=True),
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='estimated_size',
            field=models.CharField(blank=True, help_text='Estimated size: small, medium, large', max_length=20),
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='logos_detected',
            field=models.JSONField(default=list, help_text='Detected logos/brands (e.g., Amazon, FedEx)'),
        ),
        migrations.AlterField(
            model_name='captureanalysis',
            name='processing_time_ms',
            field=models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='quiet_hours_end',
            field=models.TimeField(default=datetime.time(7, 0), help_text='End of quiet hours'),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='quiet_hours_start',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Start of quiet hours (no email/SMS)'),
        ),
    ]
