# Generated by Django 5.1.3 on 2025-11-26 23:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_captureanalysis_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('plus', 'Plus'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=10)),
                ('notification_limit', models.IntegerField(help_text='Monthly notification limit (0 = unlimited)')),
                ('data_limit_mb', models.IntegerField(help_text='Monthly data limit in MB (0 = unlimited)')),
                ('overage_notification_price', models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Price per notification over limit', max_digits=10)),
                ('overage_data_price_per_mb', models.DecimalField(decimal_places=4, default=Decimal('0.01'), help_text='Price per MB over data limit', max_digits=10)),
                ('features', models.JSONField(default=list, help_text='List of feature names')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When device was activated by customer', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='battery_percentage',
            field=models.IntegerField(blank=True, help_text='Battery percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When device was claimed', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, help_text='Current firmware version', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='lifecycle_state',
            field=models.CharField(choices=[('pre_activation', 'Pre-Activation'), ('active_subscription', 'Active Subscription'), ('suspended', 'Suspended'), ('returned', 'Returned'), ('decommissioned', 'Decommissioned')], default='pre_activation', help_text='Device lifecycle state', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, help_text='Device location description', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='Customer-assigned device name', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='power_state',
            field=models.CharField(choices=[('sleep', 'Sleep'), ('awake', 'Awake'), ('uploading', 'Uploading'), ('charging', 'Charging')], default='sleep', help_text='Current power state', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Free Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_end', models.DateTimeField(blank=True, help_text='End of grace period after failed payment', null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='devices.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('notification_count', models.IntegerField(default=0, help_text='Number of mail detections/notifications')),
                ('data_used_mb', models.DecimalField(decimal_places=2, default=0, help_text='Data used in MB', max_digits=10)),
                ('notification_limit', models.IntegerField(help_text='Plan notification limit')),
                ('data_limit_mb', models.IntegerField(help_text='Plan data limit in MB')),
                ('overage_notifications', models.IntegerField(default=0)),
                ('overage_data_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overage_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_usage', to='devices.device')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='devices.customersubscription')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['device', 'year', 'month'], name='devices_dat_device__62bce1_idx')],
                'unique_together': {('device', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Payment description')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure if failed')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='devices.customersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', '-created_at'], name='devices_pay_subscri_1bff5d_idx'), models.Index(fields=['status', '-created_at'], name='devices_pay_status_857b88_idx')],
            },
        ),
    ]
