# Generated by Django 5.1.3 on 2025-12-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_ir_sensor_add_trigger_type'),
        ('devices', '0013_subscriptionplan_device_activated_at_and_more'),
    ]

    operations = [
    ]
